### ISSUE TITLE
Had errors trying to run on Manjaro

### ISSUE THREAD

**Issue by DeeWykoff** [ssokolow/gtk-recent-scrubber#5]
Got various errors.

```
   File "./gtk_cleanup.py", line 136
     except ValueError, err:
                      ^
 SyntaxError: invalid syntax
```

and so on.

I changed the first line to:
# !/usr/bin/env python2

(added the 2 on the end) and that appears to have sorted it out.

**Comment by ssokolow** [comment]
In other words, Manjaro is like Arch and defines "python" as "python3" rather than "python2". 

There's quite a bit of disagreement over that since it's essentially arbitrary downstream breakage of an upstream API but enough distros should have added a "python2" link for me to be able to get away with that now.
